cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build_and_deploy_all
  - build_and_deploy

.scalingo_deployment: &scalingo_scripts |
  cd $APP
  tar -cvzf $APP.tar.gz target
  scalingo --app $APP --region $REGION deploy $APP.tar.gz

#BEGIN PREPROD
build_and_deploy_all_preprod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy_all
  script:
    - mvn clean install -DskipTests

    - mkdir -p $SCALINGO_API_TENANT_PREPROD/target
    - cp dossierfacile-api-tenant/target/*.jar $SCALINGO_API_TENANT_PREPROD/target/
    - cp dossierfacile-api-tenant/Procfile $SCALINGO_API_TENANT_PREPROD/target/
    - cp dossierfacile-api-tenant/system.properties $SCALINGO_API_TENANT_PREPROD/target/

    - mkdir -p $SCALINGO_BO_PREPROD/target
    - cp bo/target/*.jar $SCALINGO_BO_PREPROD/target/
    - cp bo/Procfile $SCALINGO_BO_PREPROD/target/
    - cp bo/system.properties $SCALINGO_BO_PREPROD/target/

    - mkdir -p $SCALINGO_OWNER_PREPROD/target
    - cp front-owner/target/*.jar $SCALINGO_OWNER_PREPROD/target/
    - cp front-owner/Procfile $SCALINGO_OWNER_PREPROD/target/
    - cp front-owner/system.properties $SCALINGO_OWNER_PREPROD/target/

    - mkdir -p $SCALINGO_PROCESS_FILE_PREPROD/target
    - cp processFile/target/*.jar $SCALINGO_PROCESS_FILE_PREPROD/target/
    - cp processFile/Procfile $SCALINGO_PROCESS_FILE_PREPROD/target/
    - cp processFile/system.properties $SCALINGO_PROCESS_FILE_PREPROD/target/

    - mkdir -p $SCALINGO_PDF_PREPROD/target
    - cp dossierfacile-pdf-generator/target/*.jar $SCALINGO_PDF_PREPROD/target/
    - cp dossierfacile-pdf-generator/Procfile $SCALINGO_PDF_PREPROD/target/
    - cp dossierfacile-pdf-generator/system.properties $SCALINGO_PDF_PREPROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PREPROD

    - export REGION=$SCALINGO_REGION_PREPROD

    - export APP=$SCALINGO_API_TENANT_PREPROD
    - *scalingo_scripts
    - cd ..

    - export APP=$SCALINGO_BO_PREPROD
    - *scalingo_scripts
    - cd ..

    - export APP=$SCALINGO_OWNER_PREPROD
    - *scalingo_scripts
    - cd ..

    - export APP=$SCALINGO_PROCESS_FILE_PREPROD
    - *scalingo_scripts
    - cd ..

    - export APP=$SCALINGO_PDF_PREPROD
    - *scalingo_scripts
    - cd ..
  only:
    - develop
  when: manual

api_tenant_preprod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy
  script:
    - mvn -f dossierfacile-common-library/pom.xml clean install -DskipTests
    - mvn -f dossierfacile-api-tenant/pom.xml clean install -DskipTests

    - mkdir -p $SCALINGO_API_TENANT_PREPROD/target
    - cp dossierfacile-api-tenant/target/*.jar $SCALINGO_API_TENANT_PREPROD/target/
    - cp dossierfacile-api-tenant/Procfile $SCALINGO_API_TENANT_PREPROD/target/
    - cp dossierfacile-api-tenant/system.properties $SCALINGO_API_TENANT_PREPROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PREPROD

    - export REGION=$SCALINGO_REGION_PREPROD
    - export APP=$SCALINGO_API_TENANT_PREPROD
    - *scalingo_scripts
  only:
    - develop
  when: manual

bo_preprod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy
  script:
    - mvn -f dossierfacile-common-library/pom.xml clean install -DskipTests
    - mvn -f bo/pom.xml clean install -DskipTests

    - mkdir -p $SCALINGO_BO_PREPROD/target
    - cp bo/target/*.jar $SCALINGO_BO_PREPROD/target/
    - cp bo/Procfile $SCALINGO_BO_PREPROD/target/
    - cp bo/system.properties $SCALINGO_BO_PREPROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PREPROD

    - export REGION=$SCALINGO_REGION_PREPROD
    - export APP=$SCALINGO_BO_PREPROD
    - *scalingo_scripts
  only:
    - develop
  when: manual

owner_preprod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy
  script:
    - mvn -f dossierfacile-common-library/pom.xml clean install -DskipTests
    - mvn -f front-owner/pom.xml clean install -DskipTests

    - mkdir -p $SCALINGO_OWNER_PREPROD/target
    - cp front-owner/target/*.jar $SCALINGO_OWNER_PREPROD/target/
    - cp front-owner/Procfile $SCALINGO_OWNER_PREPROD/target/
    - cp front-owner/system.properties $SCALINGO_OWNER_PREPROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PREPROD

    - export REGION=$SCALINGO_REGION_PREPROD
    - export APP=$SCALINGO_OWNER_PREPROD
    - *scalingo_scripts
  only:
    - develop
  when: manual

process_file_preprod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy
  script:
    - mvn -f dossierfacile-common-library/pom.xml clean install -DskipTests
    - mvn -f processFile/pom.xml clean install -DskipTests

    - mkdir -p $SCALINGO_PROCESS_FILE_PREPROD/target
    - cp processFile/target/*.jar $SCALINGO_PROCESS_FILE_PREPROD/target/
    - cp processFile/Procfile $SCALINGO_PROCESS_FILE_PREPROD/target/
    - cp processFile/system.properties $SCALINGO_PROCESS_FILE_PREPROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PREPROD

    - export REGION=$SCALINGO_REGION_PREPROD
    - export APP=$SCALINGO_PROCESS_FILE_PREPROD
    - *scalingo_scripts
  only:
    - develop
  when: manual

pdf_preprod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy
  script:
    - mvn -f dossierfacile-common-library/pom.xml clean install -DskipTests
    - mvn -f dossierfacile-pdf-generator/pom.xml clean install -DskipTests

    - mkdir -p $SCALINGO_PDF_PREPROD/target
    - cp dossierfacile-pdf-generator/target/*.jar $SCALINGO_PDF_PREPROD/target/
    - cp dossierfacile-pdf-generator/Procfile $SCALINGO_PDF_PREPROD/target/
    - cp dossierfacile-pdf-generator/system.properties $SCALINGO_PDF_PREPROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PREPROD

    - export REGION=$SCALINGO_REGION_PREPROD
    - export APP=$SCALINGO_PDF_PREPROD
    - *scalingo_scripts
  only:
    - develop
  when: manual
#END PREPROD

#BEGIN PROD
build_and_deploy_all_prod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy_all
  script:
    - mvn clean install -DskipTests

    - mkdir -p $SCALINGO_API_TENANT_PROD/target
    - cp dossierfacile-api-tenant/target/*.jar $SCALINGO_API_TENANT_PROD/target/
    - cp dossierfacile-api-tenant/Procfile $SCALINGO_API_TENANT_PROD/target/
    - cp dossierfacile-api-tenant/system.properties $SCALINGO_API_TENANT_PROD/target/

    - mkdir -p $SCALINGO_BO_PROD/target
    - cp bo/target/*.jar $SCALINGO_BO_PROD/target/
    - cp bo/Procfile $SCALINGO_BO_PROD/target/
    - cp bo/system.properties $SCALINGO_BO_PROD/target/

    - mkdir -p $SCALINGO_OWNER_PROD/target
    - cp front-owner/target/*.jar $SCALINGO_OWNER_PROD/target/
    - cp front-owner/Procfile $SCALINGO_OWNER_PROD/target/
    - cp front-owner/system.properties $SCALINGO_OWNER_PROD/target/

    - mkdir -p $SCALINGO_PROCESS_FILE_PROD/target
    - cp processFile/target/*.jar $SCALINGO_PROCESS_FILE_PROD/target/
    - cp processFile/Procfile $SCALINGO_PROCESS_FILE_PROD/target/
    - cp processFile/system.properties $SCALINGO_PROCESS_FILE_PROD/target/

    - mkdir -p $SCALINGO_PDF_PROD/target
    - cp dossierfacile-pdf-generator/target/*.jar $SCALINGO_PDF_PROD/target/
    - cp dossierfacile-pdf-generator/Procfile $SCALINGO_PDF_PROD/target/
    - cp dossierfacile-pdf-generator/system.properties $SCALINGO_PDF_PROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PROD

    - export REGION=$SCALINGO_REGION_PROD

    - export APP=$SCALINGO_API_TENANT_PROD
    - *scalingo_scripts
    - cd ..

    - export APP=$SCALINGO_BO_PROD
    - *scalingo_scripts
    - cd ..

    - export APP=$SCALINGO_OWNER_PROD
    - *scalingo_scripts
    - cd ..

    - export APP=$SCALINGO_PROCESS_FILE_PROD
    - *scalingo_scripts
    - cd ..

    - export APP=$SCALINGO_PDF_PROD
    - *scalingo_scripts
    - cd ..
  only:
    - master
  when: manual

api_tenant_prod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy
  script:
    - mvn -f dossierfacile-common-library/pom.xml clean install -DskipTests
    - mvn -f dossierfacile-api-tenant/pom.xml clean install -DskipTests

    - mkdir -p $SCALINGO_API_TENANT_PROD/target
    - cp dossierfacile-api-tenant/target/*.jar $SCALINGO_API_TENANT_PROD/target/
    - cp dossierfacile-api-tenant/Procfile $SCALINGO_API_TENANT_PROD/target/
    - cp dossierfacile-api-tenant/system.properties $SCALINGO_API_TENANT_PROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PROD

    - export REGION=$SCALINGO_REGION_PROD
    - export APP=$SCALINGO_API_TENANT_PROD
    - *scalingo_scripts
  only:
    - master
  when: manual

bo_prod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy
  script:
    - mvn -f dossierfacile-common-library/pom.xml clean install -DskipTests
    - mvn -f bo/pom.xml clean install -DskipTests

    - mkdir -p $SCALINGO_BO_PROD/target
    - cp bo/target/*.jar $SCALINGO_BO_PROD/target/
    - cp bo/Procfile $SCALINGO_BO_PROD/target/
    - cp bo/system.properties $SCALINGO_BO_PROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PROD

    - export REGION=$SCALINGO_REGION_PROD
    - export APP=$SCALINGO_BO_PROD
    - *scalingo_scripts
  only:
    - master
  when: manual

owner_prod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy
  script:
    - mvn -f dossierfacile-common-library/pom.xml clean install -DskipTests
    - mvn -f front-owner/pom.xml clean install -DskipTests

    - mkdir -p $SCALINGO_OWNER_PROD/target
    - cp front-owner/target/*.jar $SCALINGO_OWNER_PROD/target/
    - cp front-owner/Procfile $SCALINGO_OWNER_PROD/target/
    - cp front-owner/system.properties $SCALINGO_OWNER_PROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PROD

    - export REGION=$SCALINGO_REGION_PROD
    - export APP=$SCALINGO_OWNER_PROD
    - *scalingo_scripts
  only:
    - master
  when: manual

process_file_prod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy
  script:
    - mvn -f dossierfacile-common-library/pom.xml clean install -DskipTests
    - mvn -f processFile/pom.xml clean install -DskipTests

    - mkdir -p $SCALINGO_PROCESS_FILE_PROD/target
    - cp processFile/target/*.jar $SCALINGO_PROCESS_FILE_PROD/target/
    - cp processFile/Procfile $SCALINGO_PROCESS_FILE_PROD/target/
    - cp processFile/system.properties $SCALINGO_PROCESS_FILE_PROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PROD

    - export REGION=$SCALINGO_REGION_PROD
    - export APP=$SCALINGO_PROCESS_FILE_PROD
    - *scalingo_scripts
  only:
    - master
  when: manual

pdf_prod:
  image: maven:3.6.3-openjdk-15-slim
  stage: build_and_deploy
  script:
    - mvn -f dossierfacile-common-library/pom.xml clean install -DskipTests
    - mvn -f dossierfacile-pdf-generator/pom.xml clean install -DskipTests

    - mkdir -p $SCALINGO_PDF_PROD/target
    - cp dossierfacile-pdf-generator/target/*.jar $SCALINGO_PDF_PROD/target/
    - cp dossierfacile-pdf-generator/Procfile $SCALINGO_PDF_PROD/target/
    - cp dossierfacile-pdf-generator/system.properties $SCALINGO_PDF_PROD/target/

    - apt update -y
    - apt install -y curl
    - curl -k -O https://cli-dl.scalingo.io/install && bash install
    - scalingo login --api-token $SCALINGO_API_TOKEN_PROD

    - export REGION=$SCALINGO_REGION_PROD
    - export APP=$SCALINGO_PDF_PROD
    - *scalingo_scripts
  only:
    - master
  when: manual
#END PROD
